# Testing this out

title: TeachYourselfToLearn blogg
email: evelin.foxell@purplescout.se
description: > # this means to ignore newlines until "baseurl:"
  En blogg för min lilla hemsida med självstudiematerial i hur du lär dig själv
  att programmera.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evelinfoxell.github.io/TeachYourselfToLearn" # the base hostname & protocol for your site
github_username:  evelinfoxell

# Build settings
markdown: kramdown